version: "3"

services:
  b2w-api:
    build: .
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/b2w"
      SPRING_DATA_MONGODB_USERNAME: "root"
      SPRING_DATA_MONGODB_PASSWORD: "root"
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "b2w"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "root"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "root"

    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "b2w"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
